<a href="https://colab.research.google.com/github/introvet7/CHMP/blob/main/%D0%A7%D0%9C%D0%9F_%D0%9F%D0%A04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Кияшко Ілля Олегович
Лабораторна робота №4

Варіант 8

Група 2-8


In [2]:
import numpy as np

# Завдання 1: Знайти матрицю С = 𝐴𝐵 − 𝐵𝐴

In [15]:
import numpy as np

A = np.array([[2, 3, 1],
              [-1, 1, 0],
              [1, 2, -1]])

B = np.array([[1, 2, 1],
              [0, 1, 2],
              [3, 1, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)
C = AB - BA
print("Матриця C:")
print(C)


Матриця C:
[[ 4  1  9]
 [-2 -6  3]
 [-8 -9  2]]



# Завдання 2: Піднести матриці до степеня

In [16]:
import numpy as np

A = np.array([[5, 0, 0, 0],
              [0, -2, 0, 0],
              [0, 0, 3, 0],
              [0, 0, 0, 2]])

A_squared = np.linalg.matrix_power(A, 2)

print("Матриця A в квадраті:")
print(A_squared)

Матриця A в квадраті:
[[25  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0  4]]


# Завдання 3: Знайти добуток матриць

In [11]:
E = np.array([[3, 5],
              [6, -1]])

F = np.array([[2, 1],
              [-3, 2]])

product = np.dot(E, F)

print("Результат множення матриць E і F:")
print(product)


Результат множення матриць E і F:
[[-9 13]
 [15  4]]


# Завдання 4: Обчислити визначники

In [17]:
import numpy as np

A = np.array([[2, 3, 4],
              [1, 0, 6],
              [7, 8, 9]])

determinant = np.linalg.det(A)

print("Визначник матриці :", determinant)

Визначник матриці : 35.00000000000001



# Завдання 5: Обчислення визначника матриці


In [9]:
B = np.array([[1, 2, 3, 4],
              [-2, 1, -4, 3],
              [3, -4, -1, 2],
              [4, 3, -2, -1]])

determinant = np.linalg.det(B)

print("Визначник матриці B:")
print(determinant)


Визначник матриці B:
900.0000000000009


# Завдання 6: Знаходження оберненої матриці


In [8]:
C = np.array([[1, 2, -3],
              [0, 1, 2],
              [0, 0, 1]])

inverse_C = np.linalg.inv(C)

print("Обернена матриця C:")
print(inverse_C)


Обернена матриця C:
[[ 1. -2.  7.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]



# Завдання 7: Обчислення рангу матриці

In [6]:
G = np.array([[1, 2, 3, 4],
              [3, -1, 2, 5],
              [1, 2, 3, 4],
              [1, 3, 4, 5]])

rank_G = np.linalg.matrix_rank(G)

print("Ранг матриці G:")
print(rank_G)


Ранг матриці G:
2


# Завдання 8: Розв'язання систему лінійних рівнянь, матричним методом (тобто обчислити обернену матрицю) і м. Гауса методом Гаусса


In [10]:
import numpy as np

# Матричний метод
def matrix_method(coefficients, constants):
    inverse_matrix = np.linalg.inv(coefficients)
    return np.dot(inverse_matrix, constants)

# Метод Крамера
def cramer_method(coefficients, constants):
    det_coefficients = np.linalg.det(coefficients)
    solutions = []
    for i in range(len(coefficients)):
        modified_coefficients = np.copy(coefficients)
        modified_coefficients[:, i] = constants
        solutions.append(round(np.linalg.det(modified_coefficients) / det_coefficients, 1))  # Округлюємо до десятих
    return solutions

# Метод Гауса
def gauss_method(a, b):
    n = len(b)

    for k in range(0, n-1):
        for i in range(k+1, n):
            if a[i, k] != 0.0:
                lam = a[i, k] / a[k, k]
                a[i, k+1:n] = a[i, k+1:n] - lam * a[k, k+1:n]
                b[i] = b[i] - lam * b[k]

    x = np.zeros(n)
    for k in range(n-1, -1, -1):
        x[k] = (b[k] - np.dot(a[k, k+1:n], x[k+1:n])) / a[k, k]

    return x

def main():
    # Матриця A і вектор B для розв'язку системи рівнянь Ax = B
    a = np.array([[1.0, 2.0, -1.0],
                  [3.0, 4.0, 1.0],
                  [5.0, 1.0, -3.0]])

    b = np.array([-3.0, 1.0, -2.0])

    # Матричний метод
    x_matrix = matrix_method(a, b)
    print("Матричний метод:", x_matrix)

    # Метод Крамера
    x_cramer = cramer_method(a, b)
    print("Метод Крамера:", x_cramer)

    # Метод Гауса
    x_gauss = gauss_method(a, b)
    print("Метод Гауса:", x_gauss)

if __name__ == "__main__":
    main()


Матричний метод: [ 1. -1.  2.]
Метод Крамера: [1.0, -1.0, 2.0]
Метод Гауса: [ 1. -1.  2.]


# Завдання 8: Розв’язати 1 завдання з наведених нижче.

№4

Створіть прямокутну матрицю A, яка має N рядків і M стовпців з випадковими елементами. Знайдіть суму елементів всієї матриці. Визначте, яку долю в цій сумі складає сума елементів кожного стовпця.

In [18]:
import numpy as np

# Введіть розміри матриці N x M
N = 5
M = 4

# Створення матриці A з випадковими цілими числами від -10 до 10
A = np.random.randint(-10, 11, (N, M))

# Знаходження суми всіх елементів матриці
total_sum = np.sum(A)

# Знаходження суми елементів у кожному стовпці
column_sums = np.sum(A, axis=0)

# Визначення частки суми елементів кожного стовпця від загальної суми
column_ratios = column_sums / total_sum

print("Матриця A:")
print(A)
print("\nСума всіх елементів матриці:", total_sum)
print("\nСуми елементів у кожному стовпці:", column_sums)
print("\nЧастка суми елементів кожного стовпця від загальної суми:")
print(column_ratios)


Матриця A:
[[  5   7  -1   0]
 [  3  -7 -10   1]
 [ -9  -5   2   1]
 [ -5  -3  -7   0]
 [ -9  -6  -4  -1]]

Сума всіх елементів матриці: -48

Суми елементів у кожному стовпці: [-15 -14 -20   1]

Частка суми елементів кожного стовпця від загальної суми:
[ 0.3125      0.29166667  0.41666667 -0.02083333]
